name: hird
description: Mobile App for displaying data from HWiNFO using the HIRD Server.
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  protobuf: ^2.0.1
  grpc: ^3.0.2
  network_info_plus: ^2.1.2
  fading_edge_scrollview: ^2.0.1
  connectivity_plus: ^2.2.0
  wakelock: ^0.6.1+1
  syncfusion_flutter_sliders: ^19.4.48
  syncfusion_flutter_gauges: ^19.4.48
  get_it: ^7.2.0
  freezed_annotation:
  animated_theme_switcher: ^2.0.6
  device_info_plus: ^3.2.1
  expandable: ^5.0.1
  back_button_interceptor: ^5.0.2
  ping_discover_network:
    git:
      url: https://github.com/deakjahn/ping_discover_network.git

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner:
  freezed:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/hw/cpu.png
    - assets/hw/gpu.png
    - assets/hw/hdd.png
    - assets/hw/m2_ssd.png
    - assets/hw/mobo.png
    - assets/hw/ram.png
    - assets/hw/sata_ssd.png
    - assets/hw/desktop.png
    - assets/hw/laptop.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"