# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Android

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#####################################
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
#####################################
      - name: Prepare Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'upload-keystore.jks'
          fileDir: './android/app/'
          encodedString: ${{ secrets.UPLOAD_KEYSTORE }}
######################################
      - name: Flutter Build Android
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
      - run: flutter pub get
      - run: flutter build apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
      - run: flutter build appbundle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
########################################
      - name: Create release with APK
        uses: softprops/action-gh-release@v0.1.14
        with:
          body_path: CHANGELOG.md
          files: |
            build/app/outputs/flutter-apk/app-release.apk
########################################
      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONFIG_JSON }}
          packageName: com.clicksrv.hird.client
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: alpha
          inAppUpdatePriority: 5
          userFraction: 1
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
